# Generated by Django 5.1.5 on 2025-03-31 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(default='petrol', max_length=50)),
                ('mileage', models.CharField(default='0', max_length=50)),
                ('transmission', models.CharField(default='manual', max_length=50)),
                ('color', models.CharField(default='Black', max_length=50)),
                ('year', models.IntegerField()),
                ('photo', models.ImageField(default='icon.jpg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(default='petrol', max_length=50)),
                ('mileage', models.CharField(default='0', max_length=50)),
                ('transmission', models.CharField(default='manual', max_length=50)),
                ('color', models.CharField(default='Black', max_length=50)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
