# Generated by Django 5.1.5 on 2025-04-03 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycarproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
