# Generated by Django 5.1.5 on 2025-04-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarproject', '0002_remove_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_name',
            field=models.CharField(default='reagan', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_phone',
            field=models.CharField(default='+256 5685431', max_length=15),
        ),
    ]
