# Generated by Django 5.1.5 on 2025-04-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarproject', '0003_order_buyer_name_order_buyer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
